[tool.poetry]
name = "techstorm-ds16-group3"
version = "0.1.0"
description = ""
authors = ["Andriy414414 <133632261+Andriy414414@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
absl-py = "^2.1.0"
astunparse = "^1.6.3"
cachetools = "^5.3.2"
certifi = "^2024.2.2"
charset-normalizer = "^3.3.2"
dm-tree = "^0.1.8"
django = "^5.0.4"
flatbuffers = "^23.5.26"
gast = "^0.5.4"
google-auth = "^2.27.0"
google-auth-oauthlib = "^1.2.0"
google-pasta = "^0.2.0"
grpcio = "^1.60.1"
h5py = "^3.10.0"
idna = "^3.6"
keras = "*"
libclang = "^16.0.6"
markdown = "^3.5.2"
markdown-it-py = "^3.0.0"
markupsafe = "^2.1.5"
matplotlib = "*"
mdurl = "^0.1.2"
ml-dtypes = ">=0.3.1,<0.4.0"
namex = "^0.0.7"
numpy = "^1.26.4"
oauthlib = "^3.2.2"
opt-einsum = "^3.3.0"
packaging = "^23.2"
pillow = "^10.2.0"
protobuf = "^4.25.2"
psycopg2-binary = "^2.9.9"
pyasn1 = "^0.5.1"
pyasn1-modules = "^0.3.0"
pygments = "^2.17.2"
python-dotenv = "^1.0.1"
requests = "^2.31.0"
requests-oauthlib = "^1.3.1"
rich = "^13.7.0"
rsa = "^4.9"
six = "^1.16.0"
tensorboard = "^2.15.2"
tensorboard-data-server = "^0.7.2"
tensorflow = "^2.16.1"
tensorflow-estimator = "^2.15.0"
tensorflow-io-gcs-filesystem = "~0.31"
termcolor = "^2.4.0"
typing-extensions = "^4.9.0"
tzdata = "*"
urllib3 = "^2.2.0"
werkzeug = "^3.0.1"
wrapt = "^1.14.1"
wand = "^0.6.13"
cloudinary = "^1.40.0"
environ = "^1.0"
django-environ = "^0.11.2"
django-storages = "^1.14.2"
boto3 = "^1.34.97"
django-allauth = "0.59.0"
pandas = "^2.2.2"
tabulate = "^0.9.0"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
